<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {
        $qb = $this->createQueryBuilder('c')
          ->join('c.anecdotes', 'a')
          ->addSelect('a')
          ->orderBy('c.name', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
























