# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

# Must be consistent with the language of the installation
# Regexp must be useable by preg_match
# FR
    anecdote_description_regexp: '/[bB]ref, .* tout donné.*$/'
# EN
#     anecdote_description_regexp: '/I have given you all!$/'

services:
    markdown:
        class: AppBundle\Utils\Markdown

    markdown.twig.app_extension:
        public:    false
        class:     AppBundle\Twig\MarkdownExtension
        arguments: ["@markdown", "%locale%"]
        tags:
            - { name: twig.extension }

    validator.anecdote.description:
        class: AppBundle\Validator\Constraints\AnecdoteDescriptionValidator
        arguments: ['%anecdote_description_regexp%']
        tags:
            - { name: validator.constraint_validator, alias: validator.anecdote.description }